version: '3.6'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: streamuploader
    ports:
      - '4563-4584:4563-4584'
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=development_mock
      - AWS_SECRET_ACCESS_KEY=development_mock
      - PORT_WEB_UI=8080
    volumes:
      - './.localstack:/tmp/localstack/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
